app = "streamlit-ssn"  # <-- Change this to your Fly.io app name
primary_region = "lax"

[[services]]
  internal_port = 8501
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443